### ISSUE TITLE
Add the ability to pin freely

### ISSUE THREAD

**Issue by cCaptainn** [MysteriousMilk/ExpertExplorer#3]
Your mod is a perfect addition to NoMap runs but it would be even better with the ability to freely place a pin at a location that you mark by pressing the assigned hotkey.

**Comment by MysteriousMilk** [comment]
Added capability to set some common pins with a hotkey(s)
- RightCtrl + Numpad0 = Pin Home or Town
- RightCtrl + Numpad1 = Pin a point of interest
- RightCtrl + Numpad2 = Pin an ore deposit
- RightCtrl + Numpad3 = Pin a camp
- RightCtrl + Numpad4 = Pin a dungeon or crypt
- RightCtrl + Numpad5 = Pin a portal

Hotkeys and pin text are configurable in the mod's config file
Added additional configuration option for hiding the notification when a location is discovered
