### ISSUE TITLE
Version match issue with linux dedicated server

### ISSUE THREAD

**Issue by jordan2718** [MysteriousMilk/ExpertExplorer#5]
Hi, I have an issue when this mod is installed. The game reports a server mismatch issue when installed on a Linux based dedicated server. Seems fine on Windows based dedicated servers. See issue 436 on the Jotunn github page that I raised while troubleshooting. https://github.com/Valheim-Modding/Jotunn/issues/436

I have 2 Jotunn based mods so far, this one and Xportal. With ExpertExplorer installed the version mismatch shows both mods missing from the server. If I remove Xportal, the game still doesn't load with the same error. Removing ExpertExplorer fixes the issue. In the logs it mentions about unable to deserialize to get the version. I have attached the logs that contain the error. One from the working setup with windows client and windows server and the one not working with windows client and linux server.
[Client - LogOutput - windows.log](https://github.com/user-attachments/files/17170883/Client.-.LogOutput.-.windows.log)
[Client - LogOutput-Linux.log](https://github.com/user-attachments/files/17170885/Client.-.LogOutput-Linux.log)
[Server - LogOutput - Windows.log](https://github.com/user-attachments/files/17170886/Server.-.LogOutput.-.Windows.log)
[Server - LogOutput-Linux.log](https://github.com/user-attachments/files/17170887/Server.-.LogOutput-Linux.log)
![Screenshot 2024-09-26 080948](https://github.com/user-attachments/assets/107f196a-8d0e-49b5-b3be-f3e22c4026d2)
![Screenshot 2024-09-26 081107](https://github.com/user-attachments/assets/19050009-040e-4186-bf08-8d63170f8ab0)

**Comment by Sivarius** [comment]
![bug](https://github.com/user-attachments/assets/a209edbc-7557-4b86-a126-514a45430607)
same here, but with windows and not dedicated server 
Removing Expert realy fixes issue

**Comment by MysteriousMilk** [comment]
@jordan2718 It looks like it will be addressed in a new version of Jotunn (2.21.0). So, I'll update to that and we can reevaluate. I might need your help to test it because I don't have access to a linux server for testing.

**Comment by jordan2718** [comment]
Thanks, I'll install the mod again and test it some point this week and let you know how it goes
