### ISSUE TITLE
Bog Witch update breaks the mod

### ISSUE THREAD

**Issue by JDWiens** [MysteriousMilk/ExpertExplorer#6]
When I start, the screen spins fast and I cannot control my character.  This has happened I think when Ashlands dropped as well.  Disabling the mod fixes the problem.

**Comment by MysteriousMilk** [comment]
@JDWiens I will likely need a rebuild. I haven't looked at the bog witch update yet, but I'll try to get it rebuilt for the update this weekend.

**Comment by JDWiens** [comment]
Tried the update from this weekend, still getting the spinning screen, also when I reenabled the mod, I was on a boat a long way from home, but after trying the mod, then disabling it and restarting, I was back in my bed.  Is that supposed to happen?

**Comment by MysteriousMilk** [comment]
@JDWiens The recent mod release was just to address an issue with server side version checking. It does not address the bog witch update.

Friendly reminder about the PTB and mod compatibility.

Bog witch update did go live today so I will be updating this mod soon, but I won't have time until this weekend. You will see this issue closed out once it's been addressed.

**Comment by JDWiens** [comment]
Understood, thanks for the update
