### ISSUE TITLE
location names and skill name is bugged

### ISSUE THREAD

**Issue by NOBODY7478** [MysteriousMilk/ExpertExplorer#9]
![Screenshot 2024-11-26 153331](https://github.com/user-attachments/assets/86bbaaae-c69b-4ba1-ae50-d9a5fd491ffa)
![Screenshot 2024-11-26 153519](https://github.com/user-attachments/assets/f86bd68a-dd95-4852-be0f-e968023b7a1f)
![Screenshot 2024-11-26 153545](https://github.com/user-attachments/assets/d236209f-d46d-4c0b-a50b-f7ff6e62c755)

**Comment by MysteriousMilk** [comment]
Localization issue with r2modman.

Jotunn mod framework allows localizations to be added manually or automatically. This mod chooses the automatic approach which requires that the localization json files be stored in a relative path "Assets/Translations/{Language}" by default.

This mod is uploaded to Thunderstore with this directory structure, but when downloaded using r2modman, the directory structure is condensed to a single directory, breaking localization.

To fix this, I'll add in some fallback code to check the main mod directory for localization files too.
